name: novel_ide
description: 网文写作IDE Android移动端 V3
publish_to: 'none'
version: 1.5.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^5.4.3
  flutter_secure_storage: ^10.3.0
  archive: ^4.0.9
  file_picker: ^8.0.5
  share_plus: ^10.0.0
  speech_to_text: ^7.4.0
  fl_chart: ^0.68.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  uuid: ^4.4.2
  intl: ^0.19.0
  flutter_local_notifications: ^18.0.0
  permission_handler: ^11.3.1
  epubx: ^4.0.0
  webview_flutter: ^4.10.0
  charset: ^2.0.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.5
  docx_creator: ^1.2.7

dependency_overrides:
  image: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.4.0
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/tomato/
    - assets/editor/editor.html
    - assets/editor/rich_editor.js
    - assets/editor/WeReadApi.js
    - assets/editor/style.css
    - assets/editor/normalize.css
    - assets/editor/news.css
    - assets/editor/rich_display.js
    - assets/editor/style_html.js
    - assets/editor/article_display.js
